### ISSUE TITLE
NoSuchMethodError when getting records with version 3.5.0 

### ISSUE THREAD

**Issue by erdeanmich** [vert-x3/vertx-service-discovery#76]
Hi, 
I'm trying to receive service records with the getRecords method. Using vertx (and service discovery) version 3.4.2 everything works fine, but if I update both to 3.5.0 I'm getting a NoSuchMethodError. 

`java.lang.NoSuchMethodError: io.vertx.core.shareddata.AsyncMap.entries(Lio/vertx/core/Handler;)V
	at io.vertx.servicediscovery.impl.DefaultServiceDiscoveryBackend.lambda$getRecords$9(DefaultServiceDiscoveryBackend.java:159)
	at io.vertx.servicediscovery.impl.DefaultServiceDiscoveryBackend.retrieveRegistry(DefaultServiceDiscoveryBackend.java:84)
	at io.vertx.servicediscovery.impl.DefaultServiceDiscoveryBackend.getRecords(DefaultServiceDiscoveryBackend.java:155)
	at io.vertx.servicediscovery.impl.DiscoveryImpl.getRecords(DiscoveryImpl.java:410)
	at io.vertx.servicediscovery.impl.DiscoveryImpl.getRecords(DiscoveryImpl.java:404)`

Is there any way to fix this problem? 
Thank you in advance!

**Comment by cescoffier** [comment]
This is because of Vert.x Core 3.50 has added a few methods to the AsyncMap interface that are now used in Service Discovery. So you need to update Vert.x to 3.5.0, your cluster manager to this version too.
