### ISSUE TITLE
ZookeeperBridgeTest#testServiceArrivalWithSameName test failure

### ISSUE THREAD

**Issue by vietj** [vert-x3/vertx-service-discovery#98]
Currently reported in Travis.

```
Service importer io.vertx.servicediscovery.zookeeper.ZookeeperServiceImporter@57ed1a92 started 
Unhandled exception 
java.lang.AssertionError: Expected true
	at io.vertx.ext.unit.impl.TestContextImpl.reportAssertionError(TestContextImpl.java:362)
	at io.vertx.ext.unit.impl.TestContextImpl.assertTrue(TestContextImpl.java:202)
	at io.vertx.ext.unit.impl.TestContextImpl.assertTrue(TestContextImpl.java:208)
	at io.vertx.servicediscovery.zookeeper.ZookeeperBridgeTest.lambda$null$32(ZookeeperBridgeTest.java:254)
	at io.vertx.servicediscovery.impl.DiscoveryImpl.lambda$getRecords$15(DiscoveryImpl.java:414)
	at io.vertx.servicediscovery.impl.DefaultServiceDiscoveryBackend.lambda$null$8(DefaultServiceDiscoveryBackend.java:162)
	at io.vertx.servicediscovery.impl.LocalAsyncMap.entries(LocalAsyncMap.java:151)
	at io.vertx.servicediscovery.impl.DefaultServiceDiscoveryBackend.lambda$getRecords$9(DefaultServiceDiscoveryBackend.java:160)
	at io.vertx.servicediscovery.impl.DefaultServiceDiscoveryBackend.retrieveRegistry(DefaultServiceDiscoveryBackend.java:85)
	at io.vertx.servicediscovery.impl.DefaultServiceDiscoveryBackend.getRecords(DefaultServiceDiscoveryBackend.java:156)
	at io.vertx.servicediscovery.impl.DiscoveryImpl.getRecords(DiscoveryImpl.java:410)
	at io.vertx.servicediscovery.impl.DiscoveryImpl.getRecords(DiscoveryImpl.java:404)
	at io.vertx.servicediscovery.zookeeper.ZookeeperBridgeTest.lambda$testServiceArrivalWithSameName$33(ZookeeperBridgeTest.java:252)
	at io.vertx.servicediscovery.impl.DiscoveryImpl.lambda$registerServiceImporter$2(DiscoveryImpl.java:219)
	at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:125)
	at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:86)
	at io.vertx.servicediscovery.zookeeper.ZookeeperServiceImporter.lambda$null$1(ZookeeperServiceImporter.java:95)
	at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:125)
	at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:86)
	at io.vertx.servicediscovery.zookeeper.ZookeeperServiceImporter.lambda$compute$7(ZookeeperServiceImporter.java:162)
	at io.vertx.core.impl.CompositeFutureImpl.setHandler(CompositeFutureImpl.java:147)
	at io.vertx.servicediscovery.zookeeper.ZookeeperServiceImporter.compute(ZookeeperServiceImporter.java:160)
	at io.vertx.servicediscovery.zookeeper.ZookeeperServiceImporter.lambda$start$2(ZookeeperServiceImporter.java:98)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:284)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:464)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
```

https://travis-ci.org/vert-x3/vertx-service-discovery/jobs/452894382

**Comment by cescoffier** [comment]
Fixed in master.
